###############################################################################
# Secret containing MongoDB credentials
###############################################################################
apiVersion: v1
kind: Secret
metadata:
  name: unifi-mongo-credentials
  namespace: unifi
type: Opaque
data:
  # Example password: `echo -n password | base64 `
  unifi_password: "cGFzc3dvcmQ="
  root_password: "cGFzc3dvcmQ="
